pipeline {
    agent any
    tools {
        maven 'maven'
        }
    stages {
        stage('Git Checkout') {
            steps {
                git branch: 'main',
                credentialsId: 'a06e7c70-ecfc-48f7-ac37-137afc0ce5c1',
                url: 'https://github.com/navneetguraya/java.git'
                }
        }
        stage ('Compile') {
            steps {
                sh 'mvn compile'
                }
            }   
        stage('Test') {
            steps {
                sh 'mvn test'
            }
            post {
                always {
                    junit 'target/surefire-reports/*.xml'
                }
            }
        }
        stage('Deliver') {
            steps {
                sh './jenkins/scripts/deliver.sh'
            }
        }
        stage ('Creat War File') {
            steps {
                sh 'jar -cf target/classes/com/mycompany/app/App.class target/*.war'
                }
            }
            stage ('Deploy War File') {
            steps {
                sh "cp target/*.war /etc/apache-tomcat-8.5.61/webapps/"
            }
        }
    }
}
